POST https://localhost:7070/fill

###
GET https://localhost:7070/single-word-sql?filter=chair

###
GET https://localhost:7070/single-word-linq?filter=chair

###
GET https://localhost:7070/multi-word?filter=chair,plastic
